[package]
name = "ob"
version = "0.1.0"
authors = ["Oscar Bonilla <6f6231@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
